package by.rogalevich.dishesproject.controllers;

import by.rogalevich.dishesproject.entity.User;
import by.rogalevich.dishesproject.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class GreetingController {
    @Autowired // This means to get the bean called userRepository // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/welcome")
    public String welcome(@RequestParam(name = "name", required = false, defaultValue = "World") String name,
                           Model model
    ) {
        model.addAttribute("name", name);
        return "welcome";
    }

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestParam String name
            , @RequestParam String email, @RequestParam String password,  @RequestParam Boolean role) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setPassword(password);
        n.setRole(role);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping
    public String main(Model model) {
        model.addAttribute("users", userRepository.findAll());
        return "main";
    }
}


